/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_pixaurora_kitten_thoughts_scrobbler_ScrobblerSetup */

#ifndef _Included_net_pixaurora_kitten_thoughts_scrobbler_ScrobblerSetup
#define _Included_net_pixaurora_kitten_thoughts_scrobbler_ScrobblerSetup
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_pixaurora_kitten_thoughts_scrobbler_ScrobblerSetup
 * Method:    hello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_pixaurora_kitten_1thoughts_scrobbler_ScrobblerSetup_hello
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
